shell = "zsh"

[plugins.zsh_completions]
github = "zsh-users/zsh-completions"

[plugins.zsh_autosuggestions]
github = "zsh-users/zsh-autosuggestions"

[plugins.zsh_fzf_history_search]
github = "joshskidmore/zsh-fzf-history-search"
