shell = "zsh"

[templates]
defer = "{{ hooks?.pre | nl }}{% for file in files %}zsh-defer -t 0.0001 source \"{{ file }}\"\n{% endfor %}{{ hooks?.post | nl }}"

[plugins.zsh-defer]
github = "romkatv/zsh-defer"

[plugins.zsh_completions]
github = "zsh-users/zsh-completions"
apply = ["defer"]

[plugins.zsh_autosuggestions]
github = "zsh-users/zsh-autosuggestions"
apply = ["defer"]

[plugins.zsh_fzf_history_search]
github = "joshskidmore/zsh-fzf-history-search"
apply = ["defer"]
