#!/bin/bash

# @see https://github.com/b4b4r07/dotfiles/blob/master/.tmux/bin/battery

has() { type "$1" &>/dev/null; }

# get_battery returns remaining battery
get_battery() {
  local current_bat percentage

  if has "pmset"; then
    current_bat="$(pmset -g ps | grep -o '[0-9]\+%' | tr -d '%')"
  elif has "ioreg"; then
    local _battery_info _max_cap _cur_cap
    _battery_info="$(ioreg -n AppleSmartBattery)"
    _max_cap="$(echo "$_battery_info" | awk '/MaxCapacity/{print $5}')"
    _cur_cap="$(echo "$_battery_info" | awk '/CurrentCapacity/{print $5}')"
    current_bat="$(awk -v cur="$_cur_cap" -v max="$_max_cap" 'BEGIN{ printf("%.2f\n", cur/max*100) }')"
  fi

  # trim dot (e.g., 79.61 -> 79)
  percentage="${current_bat%%.*}"
  if [ -n "$percentage" ]; then
    echo "$percentage%"
  fi
}

# battery_display colourizes the battery level for tmux
battery_display() {
  local percentage
  percentage="${1:-$(get_battery)}"
  echo -e "${percentage}"
}

battery_display "$(get_battery)"
