#!/usr/bin/env bash

# Install core tools
ask() {
  printf "$* (Y/n)"
  local answer
  read answer

  case $answer in
    [yN] | [yN]es | "YES" ) return 0 ;;
    * ) return 1 ;;
  esac
}

# Homebrew
if [[ ! -x `which brew` ]]; then
  if ask "Homebrew install?"; then
    /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
    brew update
    brew upgrade --all
    brew doctor
    brew -v

    # install packages
    brew install $(cat ~/dotfiles/scripts/brew-pkg-list)

    # git-lfs
    git lfs install

    # nodebrew
    nodebrew setup

    # fpath
    fpath=(/usr/local/share/zsh/functions/ ${fpath}) | zsh
  fi
fi

# zplug
if [[ -f "${HOME}/.zplug/init.zsh" ]]; then
  if ask "zplug install?"; then
    curl -sL --proto-redir -all,https https://raw.githubusercontent.com/zplug/installer/master/installer.zsh | zsh
  fi
fi

# vim
if ask "vim install?"; then
  ~/dotfiles/scripts/vim install
fi


# symlinks
~/dotfiles/scripts/symlinks
