#!/usr/bin/env bash
mkdir -p ~/.config/nvim
mkdir -p ~/.config/tmux
mkdir -p ~/.config/wezterm
mkdir -p ~/.config/sheldon

ln -sf ~/dotfiles/Brewfile ~/.Brewfile
ln -sf ~/dotfiles/agignore ~/.agignore
ln -sf ~/dotfiles/asdfrc ~/.asdfrc
ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/coc-settings.json ~/.config/nvim/coc-settings.json
ln -sf ~/dotfiles/gitattributes ~/.gitattributes
ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/gitignore_global ~/.gitignore_global
ln -sf ~/dotfiles/hyper.js ~/.hyper.js
ln -sf ~/dotfiles/init.vim ~/.config/nvim/init.vim
ln -sf ~/dotfiles/sheldon.toml ~/.config/sheldon/plugins.toml
ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml
ln -sf ~/dotfiles/tmux.conf ~/.config/tmux/tmux.conf
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/wezterm.lua ~/.config/wezterm/wezterm.lua
ln -sf ~/dotfiles/zshrc ~/.zshrc
