#!/usr/bin/env bash
ln -sf ~/dotfiles/agignore ~/.agignore
ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/gitattributes ~/.gitattributes
ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/zshrc ~/.zshrc
ln -sf ~/dotfiles/hyper.js ~/.hyper.js

