#!/usr/bin/env bash
mkdir -p ~/.config/nvim

ln -sf ~/dotfiles/agignore ~/.agignore
ln -sf ~/dotfiles/bashrc ~/.bashrc
ln -sf ~/dotfiles/Brewfile ~/.Brewfile
ln -sf ~/dotfiles/coc-settings.json ~/.config/nvim/coc-settings.json
ln -sf ~/dotfiles/gitattributes ~/.gitattributes
ln -sf ~/dotfiles/gitconfig ~/.gitconfig
ln -sf ~/dotfiles/gitignore_global ~/.gitignore_global
ln -sf ~/dotfiles/tmux.conf ~/.tmux.conf
ln -sf ~/dotfiles/vimrc ~/.vimrc
ln -sf ~/dotfiles/init.vim ~/.config/nvim/init.vim
ln -sf ~/dotfiles/starship.toml ~/.config/starship.toml
ln -sf ~/dotfiles/zshrc ~/.zshrc
ln -sf ~/dotfiles/hyper.js ~/.hyper.js
